version: 2.1
jobs:
  build:
    docker:
      - image: fr3akyphantom/droid-builder:latest
    environment:
      TERM: "xterm-256color"
      GitHubMail: "rokibhasansagar2014@outlook.com"
      GitHubName: "rokibhasansagar"
      REPO: "android_device_xiaomi_sirius-twrp"
      VENDOR: "xiaomi"
      CODENAME: "sirius"
      # FLAVOR: "userdebug"
    working_directory: /home/builder/shrp/
    steps:
      - run:
          name: Ultimate Builder
          command: |
            wget -q https://gist.github.com/rokibhasansagar/6d75f2a618765e8d35fa9674e411f712/raw/single.sh
            source single.sh
workflows:
  version: 2
  skyhawk_core:
    jobs:
      - build
