version: 2.1
jobs:
  build:
    docker:
      - image: fr3akyphantom/droid-builder:latest
    environment:
      TERM: "xterm-256color"
      GitHubMail: "regnermax8@gmail.com"
      GitHubName: "MaxRegner"
      REPO: "device_samsung_a50dd"
      VENDOR: "samsung"
      CODENAME: "a50dd"
      # FLAVOR: "userdebug"
    working_directory: /home/builder/shrp/
    steps:
      - run:
          name: Create & Run a keep-alive shell
          command: |
            # Basic trick to ping every 8 minutes in the background
            cat \<< EOF > /tmp/act.sh
            #!/bin/bash
            while true; do
              echo -e "\n" && sleep 480
            done
            EOF
            chmod a+x /tmp/act.sh
      - run:
          name: Ultimate Builder
          command: |
            wget -q https://gist.github.com/rokibhasansagar/6d75f2a618765e8d35fa9674e411f712/raw/single.sh
            /tmp/act.sh & source single.sh
workflows:
  version: 2
  skyhawk_core:
    jobs:
      - build
