version: 2.1
jobs:
  build:
    docker:
      - image: fr3akyphantom/droid-builder:latest
    environment:
      GitHubMail: "rokibhasansagar2014@outlook.com"
      GitHubName: "rokibhasansagar"
      REPO: "recovery-device-xiaomi-rosy"
      VENDOR: "xiaomi"
      CODENAME: "rosy"
      # FLAVOR: "userdebug"
    working_directory: /home/builder/shrp/
    steps:
      - run:
          name: Ultimate Builder
          command: |
            wget -q https://gist.github.com/rokibhasansagar/6d75f2a618765e8d35fa9674e411f712/raw/single.sh
            source single.sh
workflows:
  version: 2
  skyhawk_core:
    jobs:
      - build
