version: 2.1
jobs:
  build:
    docker:
      - image: fr3akyphantom/droid-builder:latest
    environment:
      GitHubMail: "rokibhasansagar2014@outlook.com"
      GitHubName: "rokibhasansagar"
    working_directory: /home/builder/shrp/
    steps:
      - run:
          name: Ultimate Builder
          command: |
            wget -q https://gist.github.com/rokibhasansagar/29aa473411fe462262b5134975ba2fa4/raw/shrp_builder.sh
            source shrp_builder.sh
workflows:
  version: 2
  skyhawk_core:
    jobs:
      - build
